source "https://rubygems.org"

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
#gem "jekyll", "~> 3.6.2"

gem "minimal-mistakes-jekyll"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-paginate"
  gem "jekyll-feed", "~> 0.6"
  # Patch for livereload that uses the configured site when requesting livereload.js. If Docker detects
  # the host as 0.0.0.0 then browser is unable to access livereload.js
  # PR: https://github.com/RobertDeRose/jekyll-livereload/pull/20
  gem 'jekyll-livereload', :git => 'https://github.com/math0ne/jekyll-livereload.git', :ref => '7fa4ed5'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

